const users=[
 {name:'María López',email:'maria@example.com',provider:'Google',date:'02/09/2026',status:'Activo'},
 {name:'Carlos Ramírez',email:'carlos@example.com',provider:'Correo',date:'01/09/2026',status:'Activo'},
 {name:'Ana Torres',email:'ana@example.com',provider:'Google',date:'30/08/2026',status:'Activo'},
 {name:'Luis Hernández',email:'luis@example.com',provider:'Correo',date:'29/08/2026',status:'Inactivo'}
];
const tickets=[
 {id:'#SR-104',user:'María López',type:'Error',subject:'No aparece mi widget',date:'03/09/2026',status:'Pendiente'},
 {id:'#SR-103',user:'Carlos Ramírez',type:'Sugerencia',subject:'Agregar más colores',date:'03/09/2026',status:'En revisión'},
 {id:'#SR-102',user:'Ana Torres',type:'Duda',subject:'¿Cómo cambio mi horario?',date:'02/09/2026',status:'Resuelto'},
 {id:'#SR-101',user:'Luis Hernández',type:'Error',subject:'No recibe recordatorio',date:'01/09/2026',status:'Resuelto'}
];
const pages={dashboard(){return `<div class="stats"><div class="stat"><div class="label">Usuarios registrados</div><div class="num">1,284</div><span class="tag">+12.4%</span></div><div class="stat"><div class="label">Activos hoy</div><div class="num">846</div><span class="tag">66%</span></div><div class="stat"><div class="label">Reportes pendientes</div><div class="num">3</div><span class="tag red">Requieren atención</span></div><div class="stat"><div class="label">Versión actual</div><div class="num">2.2.3</div><span class="tag">Estable</span></div></div><div class="grid2"><div class="panel"><h3>Actividad de usuarios</h3><div class="row"><span>Hoy</span><b>846 usuarios</b></div><div class="bar"><span style="width:66%"></span></div><div class="row"><span>Últimos 7 días</span><b>1,173 usuarios</b></div><div class="bar"><span style="width:91%"></span></div><div class="row"><span>Últimos 30 días</span><b>1,284 usuarios</b></div><div class="bar"><span style="width:100%"></span></div></div><div class="panel"><h3>Reportes recientes</h3>${tickets.slice(0,3).map(t=>`<div class="row"><div><b>${t.subject}</b><br><small>${t.user} · ${t.type}</small></div><span class="tag ${t.status==='Pendiente'?'red':t.status==='En revisión'?'orange':''}">${t.status}</span></div>`).join('')}</div></div>`},
users(){return `<div class="panel"><h3>Usuarios</h3><input class="search" id="userSearch" placeholder="Buscar por nombre o correo..."><table class="table"><thead><tr><th>Usuario</th><th>Proveedor</th><th>Registro</th><th>Estado</th><th></th></tr></thead><tbody id="userRows">${users.map(u=>`<tr><td><b>${u.name}</b><br><small>${u.email}</small></td><td>${u.provider}</td><td>${u.date}</td><td><span class="tag ${u.status==='Inactivo'?'red':''}">${u.status}</span></td><td><button class="smallbtn">Ver</button></td></tr>`).join('')}</tbody></table></div>`},
tickets(){return `<div class="panel"><h3>Soporte y reportes</h3><table class="table"><thead><tr><th>ID</th><th>Usuario</th><th>Tipo</th><th>Asunto</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>${tickets.map((t,i)=>`<tr><td><b>${t.id}</b></td><td>${t.user}</td><td>${t.type}</td><td>${t.subject}</td><td>${t.date}</td><td><span class="tag ${t.status==='Pendiente'?'red':t.status==='En revisión'?'orange':''}">${t.status}</span></td><td><button class="smallbtn" onclick="alert('Aquí abriremos el ticket ${t.id} para responderlo.')">Abrir</button></td></tr>`).join('')}</tbody></table></div>`},
versions(){return `<div class="panel"><h3>Versiones de School Reminder</h3><div class="row"><div><b>2.2.3</b><br><small>Versión estable · actual</small></div><span class="tag">1,284 usuarios</span></div><div class="row"><div><b>2.2.2</b><br><small>Anterior</small></div><span class="tag orange">320 usuarios</span></div><div class="row"><div><b>2.1.x</b><br><small>Antiguas</small></div><span class="tag red">48 usuarios</span></div></div><div class="panel" style="margin-top:18px"><h3>Próximo lanzamiento</h3><p class="muted">Aquí podremos publicar notas de actualización, marcar una versión como recomendada y enviar avisos a los usuarios.</p><button class="smallbtn">Crear versión</button></div>`},
settings(){return `<div class="panel"><h3>Configuración del panel</h3><div class="row"><span>Modo de mantenimiento</span><span class="tag">Desactivado</span></div><div class="row"><span>Notificaciones de nuevos reportes</span><span class="tag">Activadas</span></div><div class="row"><span>Backend</span><span class="tag orange">Pendiente de conectar</span></div><p class="muted">En la siguiente etapa conectaremos Firebase Authentication, Firestore y el sistema de roles para que estos datos sean reales.</p></div>`}}
const titles={dashboard:'Resumen general',users:'Usuarios',tickets:'Reportes y soporte',versions:'Versiones',settings:'Configuración'};
function render(page='dashboard'){document.getElementById('title').textContent=titles[page];document.getElementById('content').innerHTML=pages[page]();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='users'){document.getElementById('userSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#userRows tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')}}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.page));render();
